name: gitoo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make root
    - name: make-artifact
      run: |
        cd root/host/fs
        zip -ry root.zip ./*
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: autobuild
        # A file, directory or wildcard pattern that describes what to upload
        path: root.zip
    
