name: gitoo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make root
    - name: make-artifact
      run: |
        cd root/host/fs
        zip -ry root.zip ./*
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ab
        name: Auto Build
        body: ab
        draft: false
        prerelease: true
        files: |
          root/host/fs/root.zip
          LICENSE 
    
